name: Publish Node.js package
author: 云淡然 <hi@ydr.me> (https://ydr.me)
description: 发布 Node.js 软件包

inputs:
  token:
    description: 软件包源的授权令牌
    required: true
  registry:
    description: 软件包源地址
    required: false
    default: "https://registry.npmjs.org"
  tag:
    description: 版本标签，默认为 latest
    required: false
    default: latest
  dryRun:
    description: 模拟发布
    required: false
    default: "false"
  includePrivate:
    description: 同时发布私有包
    required: false
    default: "false"
  disableProvenance:
    description: 禁用 npm 发布的来源证明
    required: false
    default: "false"
  disableSync:
    description: 禁用同步到 npmMirror.com
    required: false
    default: "false"
  disableStrip:
    description: 禁用修剪软件包中 package.json 中的字段，workspace 模式时会继承相关字段
    required: false
    default: "false"
  disableCopyLicense:
    description: 禁用复制根目录许可证文件（只在 workspace 模式启用，且软件包没有时）
    required: false
    default: "false"
  disableCopyReadme:
    description: 禁用复制根目录 README 文件（只在 workspace 模式启用，且软件包没有时）
    required: false
    default: "false"
  syncTimeout:
    description: 同步到 npmMirror.com 超时时间（秒），默认为 30 秒
    required: false
    default: "30"

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'package'
  color: 'red'

runs:
  using: node20
  main: dist/index.cjs
