name: 将 NodeJS 软件包发布到存储库
author: 云淡然 <hi@ydr.me> (https://ydr.me)
description: 将 NodeJS 软件包发布到存储库

inputs:
  token:
    description: 授权令牌
    required: true
  registry:
    description: 包源地址
    required: false
    default: "https://registry.npmjs.org"
  tag:
    description: 要发布的版本标签，默认为 latest
    required: false
    default: latest
  dryRun:
    description: 模拟发布，但不实际上传到注册表
    required: false
    default: "false"
  includePrivate:
    description: 同时发布私有包
    required: false
    default: "false"
  disableProvenance:
    description: 禁用 npm 发布的来源证明
    required: false
    default: "false"
  disableSync:
    description: 禁用同步到 npmmirror.com
    required: false
    default: "false"
  disableStrip:
    description: 禁用删除包中不需要的键，如 `scripts`、`devDependencies` 等
    required: false
    default: "false"
  disableCopyLicense:
    description: 禁用复制根目录许可证文件（如果包没有的情况）
    required: false
    default: "false"
  disableCopyReadme:
    description: 禁用复制根目录 README 文件（如果包没有的情况）
    required: false
    default: "false"
  syncTimeout:
    description: 同步超时时间（秒），默认为 30 秒
    required: false
    default: "30"

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'package'
  color: 'red'

runs:
  using: node20
  main: dist/index.cjs
