# 如果是开发合并请求到主干，则会根据约定式提交创建一个 releasePR，是一个新版本合并请求。

name: release please

on:
  push:
    branches:
      - v1

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          bump-minor-pre-major: true
