name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-node

      - name: Code lint
        run: npm run lint

      - name: Setup git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version
        run: npx release-it --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        run: node scripts/ci-version.cjs
        id: version

      - name: Tag version
        uses: jacobsvante/tag-major-minor-action@v0
        with:
            major: ${{ steps.version.outputs.major }}
            minor: ${{ steps.version.outputs.minor }}

      - name: Push
        run: git push --follow-tags
